version: '2'

services:
  nginx-php-fpm:
    image: richarvey/nginx-php-fpm:latest
    restart: always
    environment:
      GIT_REPO: 'https://github.com/mar5/animal-shelter-yii2.git'
      WEBROOT: '/var/www/html/frontend/'
      PHP_ERRORS_STDERR: 1
