version: '2'
services:
  web:
    build: .
    restart: always
    volumes:
      - ../animal-shelter-yii2:/var/www/html #php-code
    depends_on:
      - db
  nginx:
    image: nginx:1.13.8-alpine
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - web
    volumes_from:
      - web
    volumes:
      - ../compose/nginx-conf:/etc/nginx/conf.d
      - ../compose/nginx-logs:/var/log/nginx
  db:
    image: postgres:10.1-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: sds
      POSTGRES_PASSWORD: postgres
